# Generated by Django 5.2.1 on 2025-05-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='reminder_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
