# Generated by Django 5.0.4 on 2025-05-25 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
        migrations.RemoveField(
            model_name='userspotifytoken',
            name='user',
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='UserSpotifyToken',
        ),
    ]
